#!/usr/bin/env node
// Build data/levels.json from the run documented in docs/teaching.html.
//
// The doc is where the run is designed — which rung each level teaches, what factor
// it carries, what its target works out to. This turns that into the pack the game
// plays, so the two cannot describe different runs.
//
// Every level also gets a seed, chosen by playing candidate boards greedily until one
// meets the target. Greedy play is a lower bound on what a person can do, so a board
// that clears the target greedily is a board the target is reachable on. A level whose
// target could not be met would be unplayable, and nothing else would catch it.
//
// Usage:  node tools/makeLevels.js [--write]

import { readFileSync, writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
import { BLOCK, PUSH, swapPairs } from '../src/board.js';
import { greedyPlay, playableGlyphs } from '../src/level.js';
import { dealLevel } from '../src/levels.js';
import { parseArgs } from './args.js';

const HTML = new URL('../docs/teaching.html', import.meta.url);
const OUT = new URL('../data/levels.json', import.meta.url);
const RULES = JSON.parse(readFileSync(new URL('../data/rules.json', import.meta.url), 'utf8'));
const GLYPHS = playableGlyphs(
  JSON.parse(readFileSync(new URL('../data/glyphs.json', import.meta.url), 'utf8')).glyphs,
);

const ROMAN = ['I', 'II', 'III', 'IV'];
const SEED_BASE = 20260825;
const SEED_STRIDE = 7919;
const SEED_TRIES = 4000;

/** Pull the acts and their levels straight out of the run's own tables. */
export function readRun(html) {
  const acts = [...html.matchAll(
    /<div class="act" data-means='(\{.*?\})'>[\s\S]*?<span class="no">ACT ([IV]+)<\/span><span class="nm">(.*?)<\/span><span class="cfg">(.*?)<\/span>([\s\S]*?)<\/table>/g,
  )].map(([, means, roman, name, cfg, body]) => {
    const pct = (label) => {
      const m = new RegExp(`([\\d.]+)% ${label}`).exec(cfg);
      if (!m) throw new Error(`act ${roman} does not say how many ${label}`); // boundary
      return Number(m[1]) / 100;
    };
    return {
      id: name.toLowerCase().replace(/^the /, ''),
      no: roman,
      name,
      means: JSON.parse(means),
      mix: { [BLOCK]: pct('eaters'), [PUSH]: pct('pushers') },
      levels: [...body.matchAll(
        /<tr><td class="num">(\d+)<\/td><td class="num">(\d+)<\/td><td class="teach">(.*?)<\/td><td class="num">([\d.]+)<\/td><td class="num">(\d+)<\/td><td class="note">(.*?)<\/td><\/tr>/g,
      )].map(([, id, colors, teaches, factor, target, note]) => ({
        id: Number(id),
        colors: Number(colors),
        teaches: text(teaches),
        factor: Number(factor),
        target: Number(target),
        note: text(note),
      })),
    };
  });
  if (acts.length !== ROMAN.length) throw new Error(`expected ${ROMAN.length} acts, found ${acts.length}`);
  return acts;
}

const text = (s) => s
  .replace(/<[^>]+>/g, '')
  .replace(/&mdash;/g, '—').replace(/&ndash;/g, '–').replace(/&amp;/g, '&')
  .replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&#215;/g, '×')
  .replace(/&rsquo;/g, '’').replace(/&nbsp;/g, ' ')
  .replace(/\s+/g, ' ').trim();

/**
 * The first seed whose board clears `target` under greedy play.
 *
 * The candidate is dealt through `dealLevel`, the same path the game uses, because
 * dealing also draws from the seeded stream to pick each piece's drawing — validate a
 * board dealt any other way and the game gets a different one.
 *
 * @returns {{seed: number, greedy: number}}
 */
export function seedFor({ colors, target }, mix, budget, start) {
  const candidates = swapPairs({ ...RULES, colors });
  for (let i = 0; i < SEED_TRIES; i++) {
    const seed = start + i;
    const spec = { id: 0, colors, target, seed, act: { mix } };
    const dealt = dealLevel(spec, { rules: RULES, glyphs: GLYPHS, budget });
    const run = greedyPlay(dealt.board, budget, dealt.rand, candidates);
    if (run.cleared >= target) return { seed, greedy: run.cleared };
  }
  throw new Error(`no board in ${SEED_TRIES} seeds clears ${target} at ${colors} colors`); // boundary
}

function main() {
  const args = parseArgs(process.argv.slice(2), { write: { type: 'flag', default: false } });
  const acts = readRun(readFileSync(HTML, 'utf8'));
  const budget = RULES.swapBudget;

  const pack = {
    note: 'Generated by tools/makeLevels.js from the run in docs/teaching.html. Every '
      + 'seed is a board greedy play can clear the target on, so no level ships unwinnable. '
      + 'Edit the run in the doc and regenerate; editing this file alone makes the two disagree '
      + 'and the tests say so.',
    budget,
    acts: [],
  };

  console.log(`level  act        colors  factor  target  greedy  seed`);
  console.log('-'.repeat(60));
  for (const act of acts) {
    const out = { id: act.id, no: act.no, name: act.name, mix: act.mix, levels: [] };
    for (const level of act.levels) {
      const { seed, greedy } = seedFor(level, act.mix, budget, SEED_BASE + level.id * SEED_STRIDE);
      out.levels.push({ ...level, seed });
      console.log(
        `${String(level.id).padStart(5)}  ${act.name.padEnd(10)} ${String(level.colors).padStart(6)}  `
        + `${level.factor.toFixed(2).padStart(6)}  ${String(level.target).padStart(6)}  `
        + `${String(greedy).padStart(6)}  ${seed}`,
      );
    }
    pack.acts.push(out);
  }

  const total = pack.acts.reduce((n, a) => n + a.levels.length, 0);
  console.log(`\n${total} levels across ${pack.acts.length} acts, every one reachable greedily.`);
  if (args.write) {
    writeFileSync(OUT, `${JSON.stringify(pack, null, 2)}\n`);
    console.log(`wrote ${OUT.pathname}`);
  } else {
    console.log('(dry run — pass --write to save)');
  }
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) main();
